# <u>DiscoverEase : Tailored App Recommendations at Your Fingertips</u>
### <u>Project Part 2 : Database Design, Data Normalization, and Database Creation</u>

#### <u>Group 13 Team Members</u>

• Swarn Gaba (sgaba@iu.edu)

• Gandhar Ravindra Pansare (gpansar@iu.edu)

• Chaithra Lal Nair (cnair@iu.edu)

#### Importing Necessary Modules

In [1]:
# Author Name - Gandhar Ravindra Pansare

# Importing numpy for numerical computations
import numpy as np

# Importing pandas for data manipulation
import pandas as pd

In [2]:
# Author Name - Gandhar Ravindra Pansare

# Reading the Apple App Store data from a CSV file
appleAppData = pd.read_csv('appleAppData.csv')

In [3]:
# Author Name - Gandhar Ravindra Pansare

# Displaying the first few rows of the Apple App Store data
appleAppData.head()

,App_Id,App_Name,AppStore_Url,Primary_Genre,Content_Rating,Size_Bytes,Required_IOS_Version,Released,Updated,Version,...,Currency,Free,DeveloperId,Developer,Developer_Url,Developer_Website,Average_User_Rating,Reviews,Current_Version_Score,Current_Version_Reviews
0,com.hkbu.arc.apaper,A+ Paper Guide,https://apps.apple.com/us/app/a-paper-guide/id...,Education,4+,21993472.0,8.0,2017-09-28T03:02:41Z,2018-12-21T21:30:36Z,1.1.2,...,USD,True,1375410542,HKBU ARC,https://apps.apple.com/us/developer/hkbu-arc/i...,NaN,0.0,0,0.0,0
1,com.dmitriev.abooks,A-Books,https://apps.apple.com/us/app/a-books/id103157...,Book,4+,13135872.0,10.0,2015-08-31T19:31:32Z,2019-07-23T20:31:09Z,1.3,...,USD,True,1031572001,Roman Dmitriev,https://apps.apple.com/us/developer/roman-dmit...,NaN,5.0,1,5.0,1
2,no.terp.abooks,A-books,https://apps.apple.com/us/app/a-books/id145702...,Book,4+,21943296.0,9.0,2021-04-14T07:00:00Z,2021-05-30T21:08:54Z,1.3.1,...,USD,True,1457024163,Terp AS,https://apps.apple.com/us/developer/terp-as/id...,NaN,0.0,0,0.0,0
3,fr.antoinettefleur.Book1,A-F Book #1,https://apps.apple.com/us/app/a-f-book-1/id500...,Book,4+,81851392.0,8.0,2012-02-10T03:40:07Z,2019-10-29T12:40:37Z,1.2,...,USD,False,439568839,i-editeur.com,https://apps.apple.com/us/developer/i-editeur-...,NaN,0.0,0,0.0,0
4,com.imonstersoft.azdictionaryios,A-Z Synonyms Dictionary,https://apps.apple.com/us/app/a-z-synonyms-dic...,Reference,4+,64692224.0,9.0,2020-12-16T08:00:00Z,2020-12-18T21:36:11Z,1.0.1,...,USD,True,656731821,Ngov chiheang,https://apps.apple.com/us/developer/ngov-chihe...,http://imonstersoft.com,0.0,0,0.0,0

## Data Cleaning :

#### Checking for NaN ( Missing ) Values

In [4]:
# Author Name - Swarn Gaba

# Counting the number of NaN (Missing) values in each column of the appleAppData DataFrame
missing_values_count = appleAppData.isna().sum()

# Printing the number of NaN (Missing) values in each column
print("NaN (Missing) Values In Each Column :\n")
print(missing_values_count )

NaN (Missing) Values In Each Column :

App_Id                          0
App_Name                        1
AppStore_Url                    0
Primary_Genre                   0
Content_Rating                  0
Size_Bytes                    224
Required_IOS_Version            0
Released                        3
Updated                         0
Version                         0
Price                         490
Currency                        0
Free                            0
DeveloperId                     0
Developer                       0
Developer_Url                1109
Developer_Website          643988
Average_User_Rating             0
Reviews                         0
Current_Version_Score           0
Current_Version_Reviews         0
dtype: int64

#### Dropping Unnecessary Columns

In [5]:
# Author Name - Swarn Gaba

# Dropping columns 'Developer_Website', 'Developer_Url', 'Reviews', 'Current_Version_Reviews',
# 'Current_Version_Score', and 'AppStore_Url' from the appleAppData DataFrame

appleAppData.drop(['Developer_Website', 'Developer_Url', 'Reviews', 'Current_Version_Reviews', 'Current_Version_Score', 'AppStore_Url'], axis = 1, inplace = True)

In [6]:
# Author Name - Swarn Gaba

# Retrieving the column names of the appleAppData DataFrame
appleAppData.columns

Index(['App_Id', 'App_Name', 'Primary_Genre', 'Content_Rating', 'Size_Bytes',
       'Required_IOS_Version', 'Released', 'Updated', 'Version', 'Price',
       'Currency', 'Free', 'DeveloperId', 'Developer', 'Average_User_Rating'],
      dtype='object')

#### Genre-Based Data Sampling

In [7]:
# Author Name - Swarn Gaba

# Conducting data sampling based on genre
# To obtain approximately 2000 rows, this method ensures proportional representation from each genre

sampled_appleAppData = appleAppData.groupby('Primary_Genre', group_keys = False).apply(lambda x: x.sample(min(len(x), 2000 // len(appleAppData['Primary_Genre'].unique()))))

# Displaying the resulting sampled DataFrame
print("Sampled DataFrame:")
print(sampled_appleAppData)

Sampled DataFrame:
                                   App_Id                      App_Name  \
5714       com.partner-auto-7844.dupr2455         Iglesia Metropolitana
49835            com.loveteam.truyenmaquy                 Truyện Ma Quỷ
14602       com.educastudio.kabinabiishaq           Kisah Nabi Ishaq AS
7268                      maci-dev.sk.JKS                           JKS
44280        org.lionsquest-japan.lq-port               LQ-Port Library
...                                   ...                           ...
970644             com.khon.KHON2-Weather  KHON2 WX - Radar & Forecasts
943154               cc.jugem.meg.AmeshEx   AmeshEX - いつでも東京アメッシュをチェック！
745703           com.airindex.aqi.weather  Air Quality Index - Live AQI
761397           com.torsmyr.luftkvalitet                  Luftkvalitet
1222972  com.ifoxsolutions.rucheconnectee                    Ruche E&Co

        Primary_Genre Content_Rating  Size_Bytes Required_IOS_Version  \
5714             Book             4+  82405376.0                 11.4
49835            Book             9+  44352512.0                  8.0
14602            Book             4+  45379584.0                5.1.1
7268             Book             4+   7929856.0                 12.1
44280            Book             4+  57195520.0                  9.0
...               ...            ...         ...                  ...
970644        Weather             4+  82648064.0                 13.0
943154        Weather             4+   3685376.0                 13.0
745703        Weather             4+  59825152.0                 10.0
761397        Weather             4+  29945856.0                 10.0
1222972       Weather             4+  12898304.0                  8.0

                     Released               Updated  Version  Price Currency  \
5714     2021-06-10T07:00:00Z  2021-06-11T02:01:15Z    1.0.0    0.0      USD
49835    2016-06-02T08:38:06Z  2016-06-02T08:38:06Z      1.0    0.0      USD
14602    2015-06-21T23:42:43Z  2015-06-21T23:42:43Z      1.0    0.0      USD
7268     2019-10-10T07:00:00Z  2020-05-01T20:23:35Z      1.1    0.0      USD
44280    2020-04-09T07:00:00Z  2020-04-09T14:43:45Z   6.11.7    0.0      USD
...                       ...                   ...      ...    ...      ...
970644   2014-11-13T07:31:34Z  2021-09-30T14:28:25Z  5.4.701    0.0      USD
943154   2017-01-11T02:08:34Z  2021-03-29T01:09:50Z    2.0.0    0.0      USD
745703   2020-02-18T08:00:00Z  2021-09-21T20:08:11Z      1.6    0.0      USD
761397   2016-11-02T07:18:54Z  2019-12-20T18:53:47Z    0.5.4    0.0      USD
1222972  2018-06-27T03:39:48Z  2019-09-20T08:21:37Z    2.1.2    0.0      USD

         Free  DeveloperId                         Developer  \
5714     True   1571184861                    Rafael Jimenez
49835    True   1050682421                          Tran Anh
14602    True    657647590    EDUCA SISFOMEDIA INDONESIA, CV
7268     True    436802355                       Jozef Macko
44280    True   1499767485      特定非営利活動法人 青少年育成支援フォーラム(JIYD)
...       ...          ...                               ...
970644   True    488222083        LIN Television Corporation
943154   True    486154931                    KOICHIRO OISHI
745703   True    962656494  AppAspect Technologies Pvt. Ltd.
761397   True   1165806274                        Jo Torsmyr
1222972  True    592180198                   Francois Coppey

         Average_User_Rating
5714                 0.00000
49835                0.00000
14602                0.00000
7268                 0.00000
44280                0.00000
...                      ...
970644               4.61935
943154               5.00000
745703               2.14286
761397               0.00000
1222972              0.00000

[1976 rows x 15 columns]

In [8]:
# Author Name - Swarn Gaba

# Checking the shape (number of rows and columns) of the sampled Apple App Data DataFrame
sampled_appleAppData.shape

(1976, 15)

In [9]:
# Author Name - Swarn Gaba

# Counting the occurrences of each genre in the sampled Apple App Data DataFrame
genre_occurrences  = sampled_appleAppData['Primary_Genre'].value_counts()
print(genre_occurrences)

Primary_Genre
Book                      76
Business                  76
Utilities                 76
Travel                    76
Stickers                  76
Sports                    76
Social Networking         76
Shopping                  76
Reference                 76
Productivity              76
Photo & Video             76
News                      76
Navigation                76
Music                     76
Medical                   76
Magazines & Newspapers    76
Lifestyle                 76
Health & Fitness          76
Graphics & Design         76
Games                     76
Food & Drink              76
Finance                   76
Entertainment             76
Education                 76
Developer Tools           76
Weather                   76
Name: count, dtype: int64

In [10]:
# Author Name - Swarn Gaba

# Displaying the first few row_data_datas of the Sampled Apple App Store data
sampled_appleAppData.head()

,App_Id,App_Name,Primary_Genre,Content_Rating,Size_Bytes,Required_IOS_Version,Released,Updated,Version,Price,Currency,Free,DeveloperId,Developer,Average_User_Rating
5714,com.partner-auto-7844.dupr2455,Iglesia Metropolitana,Book,4+,82405376.0,11.4,2021-06-10T07:00:00Z,2021-06-11T02:01:15Z,1.0.0,0.0,USD,True,1571184861,Rafael Jimenez,0.0
49835,com.loveteam.truyenmaquy,Truyện Ma Quỷ,Book,9+,44352512.0,8.0,2016-06-02T08:38:06Z,2016-06-02T08:38:06Z,1.0,0.0,USD,True,1050682421,Tran Anh,0.0
14602,com.educastudio.kabinabiishaq,Kisah Nabi Ishaq AS,Book,4+,45379584.0,5.1.1,2015-06-21T23:42:43Z,2015-06-21T23:42:43Z,1.0,0.0,USD,True,657647590,"EDUCA SISFOMEDIA INDONESIA, CV",0.0
7268,maci-dev.sk.JKS,JKS,Book,4+,7929856.0,12.1,2019-10-10T07:00:00Z,2020-05-01T20:23:35Z,1.1,0.0,USD,True,436802355,Jozef Macko,0.0
44280,org.lionsquest-japan.lq-port,LQ-Port Library,Book,4+,57195520.0,9.0,2020-04-09T07:00:00Z,2020-04-09T14:43:45Z,6.11.7,0.0,USD,True,1499767485,特定非営利活動法人 青少年育成支援フォーラム(JIYD),0.0

#### Again, Checking for NaN ( Missing ) Values

In [11]:
# Author Name - Swarn Gaba

# Counting the number of NaN (Missing) values in each column of the Sampled appleAppData DataFrame
missing_values_count = sampled_appleAppData.isna().sum()

# Printing the number of NaN (Missing) values in each column
print("NaN (Missing) values in each column:\n")
print(missing_values_count)

NaN (Missing) values in each column:

App_Id                  0
App_Name                0
Primary_Genre           0
Content_Rating          0
Size_Bytes              0
Required_IOS_Version    0
Released                0
Updated                 0
Version                 0
Price                   0
Currency                0
Free                    0
DeveloperId             0
Developer               0
Average_User_Rating     0
dtype: int64

#### Verifying Column Data Types

In [12]:
# Author Name - Swarn Gaba

# Displaying Information about Sampled App Store Data
sampled_appleAppData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1976 entries, 5714 to 1222972
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   App_Id                1976 non-null   object
 1   App_Name              1976 non-null   object
 2   Primary_Genre         1976 non-null   object
 3   Content_Rating        1976 non-null   object
 4   Size_Bytes            1976 non-null   float64
 5   Required_IOS_Version  1976 non-null   object
 6   Released              1976 non-null   object
 7   Updated               1976 non-null   object
 8   Version               1976 non-null   object
 9   Price                 1976 non-null   float64
 10  Currency              1976 non-null   object
 11  Free                  1976 non-null   bool
 12  DeveloperId           1976 non-null   int64
 13  Developer             1976 non-null   object
 14  Average_User_Rating   1976 non-null   float64
dtypes: bool(1), float64(3), int64(1), object(10)
memory usage: 233.5+ KB

#### Transforming 'Content_Rating' Column Into Categorical Values

In [13]:
# Author Name - Gandhar Ravindra Pansare

# Defining a mapping of content ratings to age groups
age_group_mapping = {"4+": "Children", "9+": "Teen", "12+": "Teen", "17+": "Adult"}

# Mapping content ratings to age groups and creating a new 'Age_Group' column
sampled_appleAppData['Age_Group'] = sampled_appleAppData['Content_Rating'].map(age_group_mapping)

In [14]:
# Author Name - Gandhar Ravindra Pansare

# Dropping the 'Content_Rating' column from the sampled Apple App Data DataFrame
sampled_appleAppData.drop(columns=['Content_Rating'], inplace=True)

In [15]:
# Author Name - Gandhar Ravindra Pansare

# Retrieving the column names of the sampled appleAppData DataFrame
sampled_appleAppData.columns

Index(['App_Id', 'App_Name', 'Primary_Genre', 'Size_Bytes',
       'Required_IOS_Version', 'Released', 'Updated', 'Version', 'Price',
       'Currency', 'Free', 'DeveloperId', 'Developer', 'Average_User_Rating',
       'Age_Group'],
      dtype='object')

In [16]:
# Author Name - Gandhar Ravindra Pansare

# Displaying Information about Sampled App Store Data
sampled_appleAppData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1976 entries, 5714 to 1222972
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   App_Id                1976 non-null   object
 1   App_Name              1976 non-null   object
 2   Primary_Genre         1976 non-null   object
 3   Size_Bytes            1976 non-null   float64
 4   Required_IOS_Version  1976 non-null   object
 5   Released              1976 non-null   object
 6   Updated               1976 non-null   object
 7   Version               1976 non-null   object
 8   Price                 1976 non-null   float64
 9   Currency              1976 non-null   object
 10  Free                  1976 non-null   bool
 11  DeveloperId           1976 non-null   int64
 12  Developer             1976 non-null   object
 13  Average_User_Rating   1976 non-null   float64
 14  Age_Group             1976 non-null   object
dtypes: bool(1), float64(3), int64(1), object(10)
memory usage: 233.5+ KB

In [17]:
# Author Name - Gandhar Ravindra Pansare

# Displaying the first few rows of the Sampled Apple App Store data
sampled_appleAppData.head()

,App_Id,App_Name,Primary_Genre,Size_Bytes,Required_IOS_Version,Released,Updated,Version,Price,Currency,Free,DeveloperId,Developer,Average_User_Rating,Age_Group
5714,com.partner-auto-7844.dupr2455,Iglesia Metropolitana,Book,82405376.0,11.4,2021-06-10T07:00:00Z,2021-06-11T02:01:15Z,1.0.0,0.0,USD,True,1571184861,Rafael Jimenez,0.0,Children
49835,com.loveteam.truyenmaquy,Truyện Ma Quỷ,Book,44352512.0,8.0,2016-06-02T08:38:06Z,2016-06-02T08:38:06Z,1.0,0.0,USD,True,1050682421,Tran Anh,0.0,Teen
14602,com.educastudio.kabinabiishaq,Kisah Nabi Ishaq AS,Book,45379584.0,5.1.1,2015-06-21T23:42:43Z,2015-06-21T23:42:43Z,1.0,0.0,USD,True,657647590,"EDUCA SISFOMEDIA INDONESIA, CV",0.0,Children
7268,maci-dev.sk.JKS,JKS,Book,7929856.0,12.1,2019-10-10T07:00:00Z,2020-05-01T20:23:35Z,1.1,0.0,USD,True,436802355,Jozef Macko,0.0,Children
44280,org.lionsquest-japan.lq-port,LQ-Port Library,Book,57195520.0,9.0,2020-04-09T07:00:00Z,2020-04-09T14:43:45Z,6.11.7,0.0,USD,True,1499767485,特定非営利活動法人 青少年育成支援フォーラム(JIYD),0.0,Children

#### Converting 'Size_Bytes' Column From Bytes To Megabytes

In [18]:
# Author Name - Gandhar Ravindra Pansare

# Convert the 'Size_Bytes' column from bytes to megabytes
sampled_appleAppData['Size_Bytes'] = sampled_appleAppData['Size_Bytes'] / (1024 * 1024) 

# Round the 'Size_Bytes' column to 2 decimal places
sampled_appleAppData['Size_Bytes'] = sampled_appleAppData['Size_Bytes'].round(2) 

# Rename the 'Size_Bytes' column to 'Size'
sampled_appleAppData.rename(columns={'Size_Bytes': 'Size'}, inplace=True)

In [19]:
# Author Name - Gandhar Ravindra Pansare

# Displaying the first few rows of the Sampled Apple App Store data
sampled_appleAppData.head()

,App_Id,App_Name,Primary_Genre,Size,Required_IOS_Version,Released,Updated,Version,Price,Currency,Free,DeveloperId,Developer,Average_User_Rating,Age_Group
5714,com.partner-auto-7844.dupr2455,Iglesia Metropolitana,Book,78.59,11.4,2021-06-10T07:00:00Z,2021-06-11T02:01:15Z,1.0.0,0.0,USD,True,1571184861,Rafael Jimenez,0.0,Children
49835,com.loveteam.truyenmaquy,Truyện Ma Quỷ,Book,42.30,8.0,2016-06-02T08:38:06Z,2016-06-02T08:38:06Z,1.0,0.0,USD,True,1050682421,Tran Anh,0.0,Teen
14602,com.educastudio.kabinabiishaq,Kisah Nabi Ishaq AS,Book,43.28,5.1.1,2015-06-21T23:42:43Z,2015-06-21T23:42:43Z,1.0,0.0,USD,True,657647590,"EDUCA SISFOMEDIA INDONESIA, CV",0.0,Children
7268,maci-dev.sk.JKS,JKS,Book,7.56,12.1,2019-10-10T07:00:00Z,2020-05-01T20:23:35Z,1.1,0.0,USD,True,436802355,Jozef Macko,0.0,Children
44280,org.lionsquest-japan.lq-port,LQ-Port Library,Book,54.55,9.0,2020-04-09T07:00:00Z,2020-04-09T14:43:45Z,6.11.7,0.0,USD,True,1499767485,特定非営利活動法人 青少年育成支援フォーラム(JIYD),0.0,Children

In [20]:
# Author Name - Gandhar Ravindra Pansare

# Retrieving the column names of the sampled appleAppData DataFrame
sampled_appleAppData.columns

Index(['App_Id', 'App_Name', 'Primary_Genre', 'Size', 'Required_IOS_Version',
       'Released', 'Updated', 'Version', 'Price', 'Currency', 'Free',
       'DeveloperId', 'Developer', 'Average_User_Rating', 'Age_Group'],
      dtype='object')

##### The 'Required_IOS_Version' and 'Version' columns are stored as objects and cannot be converted to numerical values.

#### Converting Data Types for 'Released' and 'Updated' Columns

In [21]:
# Author Name - Chaithra Lal Nair

# Converting the 'Released' column to datetime format
sampled_appleAppData['Released'] = pd.to_datetime(sampled_appleAppData['Released'])

# Converting the 'Updated' column to datetime format
sampled_appleAppData['Updated'] = pd.to_datetime(sampled_appleAppData['Updated'])

In [22]:
# Author Name - Chaithra Lal Nair

# Dropping the 'Free' column from the sampled Apple App Data DataFrame
sampled_appleAppData.drop(columns=['Free'], inplace=True)

In [23]:
# Author Name - Chaithra Lal Nair

# Displaying Information about Sampled App Store Data
sampled_appleAppData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1976 entries, 5714 to 1222972
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   App_Id                1976 non-null   object
 1   App_Name              1976 non-null   object
 2   Primary_Genre         1976 non-null   object
 3   Size                  1976 non-null   float64
 4   Required_IOS_Version  1976 non-null   object
 5   Released              1976 non-null   datetime64[ns, UTC]
 6   Updated               1976 non-null   datetime64[ns, UTC]
 7   Version               1976 non-null   object
 8   Price                 1976 non-null   float64
 9   Currency              1976 non-null   object
 10  DeveloperId           1976 non-null   int64
 11  Developer             1976 non-null   object
 12  Average_User_Rating   1976 non-null   float64
 13  Age_Group             1976 non-null   object
dtypes: datetime64[ns, UTC](2), float64(3), int64(1), object(8)
memory usage: 231.6+ KB

#### Renaming All Columns and Resetting Index of The DataFrame

In [24]:
# Author Name - Chaithra Lal Nair

# Retrieving the column names of the sampled appleAppData DataFrame
sampled_appleAppData.columns

Index(['App_Id', 'App_Name', 'Primary_Genre', 'Size', 'Required_IOS_Version',
       'Released', 'Updated', 'Version', 'Price', 'Currency', 'DeveloperId',
       'Developer', 'Average_User_Rating', 'Age_Group'],
      dtype='object')

In [25]:
# Author Name - Chaithra Lal Nair

# Renaming columns of the DataFrame for clarity and consistency
dataframe = sampled_appleAppData.rename(columns={'App_Name': 'App_name', 'Primary_Genre': 'Genre', 
                                        'Required_IOS_Version': 'IOS_version', 'Released': 'Released_date',
                                       'Updated': 'Updated_date', 'Version': 'App_version',
                                       'DeveloperId': 'Developer_Id','Average_User_Rating': 'Avg_user_rating',
                                       'Age_Group':'Age_group'})

In [26]:
# Author Name - Chaithra Lal Nair

# Resetting the index of the DataFrame and dropping the previous index
final_data = dataframe.reset_index(drop=True)

# Displaying the first few rows of the DataFrame
final_data.head()

,App_Id,App_name,Genre,Size,IOS_version,Released_date,Updated_date,App_version,Price,Currency,Developer_Id,Developer,Avg_user_rating,Age_group
0,com.partner-auto-7844.dupr2455,Iglesia Metropolitana,Book,78.59,11.4,2021-06-10 07:00:00+00:00,2021-06-11 02:01:15+00:00,1.0.0,0.0,USD,1571184861,Rafael Jimenez,0.0,Children
1,com.loveteam.truyenmaquy,Truyện Ma Quỷ,Book,42.30,8.0,2016-06-02 08:38:06+00:00,2016-06-02 08:38:06+00:00,1.0,0.0,USD,1050682421,Tran Anh,0.0,Teen
2,com.educastudio.kabinabiishaq,Kisah Nabi Ishaq AS,Book,43.28,5.1.1,2015-06-21 23:42:43+00:00,2015-06-21 23:42:43+00:00,1.0,0.0,USD,657647590,"EDUCA SISFOMEDIA INDONESIA, CV",0.0,Children
3,maci-dev.sk.JKS,JKS,Book,7.56,12.1,2019-10-10 07:00:00+00:00,2020-05-01 20:23:35+00:00,1.1,0.0,USD,436802355,Jozef Macko,0.0,Children
4,org.lionsquest-japan.lq-port,LQ-Port Library,Book,54.55,9.0,2020-04-09 07:00:00+00:00,2020-04-09 14:43:45+00:00,6.11.7,0.0,USD,1499767485,特定非営利活動法人 青少年育成支援フォーラム(JIYD),0.0,Children

In [27]:
# Author Name - Gandhar Ravindra Pansare

# Converting the 'Released_date' and 'Updated_date' column to datetime format and formatting it as 'YYYY-MM-DD'
final_data['Released_date'] = pd.to_datetime(final_data['Released_date']).dt.strftime('%Y-%m-%d')
final_data['Updated_date'] = pd.to_datetime(final_data['Updated_date']).dt.strftime('%Y-%m-%d')

In [28]:
# Author Name - Swarn Gaba

# Saving the final DataFrame to a CSV file named 'sampled_appleAppData.csv' without including the index
final_data.to_csv('sampled_appleAppData.csv', index=False)

## Database Creation :

In [29]:
# Author Name - Swarn Gaba

# Importing the sqlite3 module for working with SQLite databases
import sqlite3  

# Importing the pandas library for data manipulation and analysis
import pandas as pd

In [30]:
# Author Name - Swarn Gaba

# Establishing a connection to the SQLite database named 'DiscoverEase.db'
conn = sqlite3.connect('DiscoverEase.db')

# Creating a cursor object to execute SQL commands
c = conn.cursor()

In [31]:
# Author Name - Swarn Gaba

# Reading the CSV file 'sampled_appleAppData.csv' into a DataFrame
data_sample = pd.read_csv(r'sampled_appleAppData.csv')

In [32]:
# Author Name - Swarn Gaba
# Defining the schema for the 'applications' table
applications_table_schema  = """
CREATE TABLE applications (
    App_Id INT PRIMARY KEY,
    App_name VARCHAR(255) NOT NULL,
    Developer_Id INT,
    Genre VARCHAR(255) NOT NULL,
    Size FLOAT,
    App_version VARCHAR(20),
    IOS_version VARCHAR(20),
    Released_date DATE,
    Updated_date DATE,
    Avg_user_rating FLOAT,
    Age_group VARCHAR(10),
    FOREIGN KEY (Developer_Id) REFERENCES developers(Developer_Id)
);
"""

# Author Name - Swarn Gaba
# Executing the SQL query to create the 'applications' table
c.execute(applications_table_schema)

# Author Name - Swarn Gaba
# Committing the changes to the database
conn.commit()

# Author Name - Gandhar Ravindra Pansare
# Defining the schema for the 'developers' table
developers_table_schema = """
CREATE TABLE developers (
    Developer_Id INT PRIMARY KEY,
    Developer VARCHAR(255) NOT NULL
);
"""

# Author Name - Gandhar Ravindra Pansare
# Executing the SQL query to create the 'developers' table
c.execute(developers_table_schema)

# Author Name - Gandhar Ravindra Pansare
# Committing the changes to the database
conn.commit()


# Author Name - Chaithra Lal Nair
# Defining the schema for the 'pricing' table
pricing_table_schema = """
CREATE TABLE pricing (
    App_Id INT PRIMARY KEY,
    Price DECIMAL(10, 2) NOT NULL,
    Currency VARCHAR(10) NOT NULL,
    FOREIGN KEY (App_Id) REFERENCES applications(App_Id)
);
"""

# Author Name - Chaithra Lal Nair
# Executing the SQL query to create the 'pricing' table
c.execute(pricing_table_schema)

# Author Name - Chaithra Lal Nair
# Committing the changes to the database
conn.commit()

## Data Insertion :

In [33]:
# Author Name - Swarn Gaba
# SQL query to insert data into the 'applications' table

applications_insert_query = """
INSERT INTO applications (App_Id, App_name, Developer_Id, Genre, Size, App_version, IOS_version, Released_date, Updated_date, Avg_user_rating, Age_group)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
"""

# Author Name - Swarn Gaba
# Iterating over rows in the DataFrame and inserting data into the 'applications' table

for idx, row_data in data_sample.iterrows():

    # Extracting values from the DataFrame row

    applications_values = (
        row_data['App_Id'], row_data['App_name'], row_data['Developer_Id'], row_data['Genre'], row_data['Size'],
        row_data['App_version'], row_data['IOS_version'], row_data['Released_date'], row_data['Updated_date'],
        row_data['Avg_user_rating'], row_data['Age_group']
    )

    # Executing the insert query with values
    c.execute(applications_insert_query, applications_values)

# Author Name - Swarn Gaba
# Committing the changes to the database
conn.commit()

# Author Name - Gandhar Ravindra Pansare
# SQL query to insert data into the 'developers' table

# Set to store unique developer IDs
unique_ids = set()

# Author Name - Gandhar Ravindra Pansare
# Iterate through the DataFrame to collect unique developer IDs

for idx, row_data in data_sample.iterrows():

    dev_id = row_data['Developer_Id']
    dev_name = row_data['Developer']
    
    # Check if developer ID is not already in the set

    if dev_id not in unique_ids:

        # Add developer ID to the set
        unique_ids.add(dev_id)

        # SQL query to insert developer details into the 'developers' table
        developers_insert_query = """
            INSERT INTO developers (Developer_Id, Developer)
            VALUES (?, ?);
            """
        
        # Values to be inserted
        developers_values = (dev_id, dev_name)

        # Execute the insert query with values
        c.execute(developers_insert_query, developers_values)

# Author Name - Gandhar Ravindra Pansare
# Committing the changes to the database
conn.commit()

# Author Name - Chaithra Lal Nair
# SQL query to insert data into the 'pricing' table

# Iterating through the DataFrame to insert pricing data into the 'pricing' table

for idx, row_data in data_sample.iterrows():
    
    # SQL query to insert pricing data into the 'pricing' table
    pricing_insert_query = """
    INSERT INTO pricing (App_Id, Price, Currency)
    VALUES (?, ?, ?)
    """

    # Values to be inserted
    pricing_values = (row_data['App_Id'], row_data['Price'], row_data['Currency'])
    
    # Execute the insert query with values
    c.execute(pricing_insert_query, pricing_values)

# Author Name - Chaithra Lal Nair
# Committing the changes to the database
conn.commit()

In [34]:
# Author Name - Chaithra Lal Nair

# Executing SQL query to retrieve the names of all tables in the SQLite database
c.execute("""SELECT name FROM sqlite_master WHERE type='table';""")

# Fetching the result of the query
DiscoverEase_created_tables = c.fetchall()

# Iterating over the list of table names
for table_name in DiscoverEase_created_tables:
    
    # Printing the name of each table
    print(table_name[0])

applications
developers
pricing

## Views Creation :

In [35]:
# Author Name - Swarn Gaba

# Top Developers View: Identifying top developers based on the number of applications they've developed
# This view, named 'TopDevelopers', calculates the total count of applications for each developer

c.execute("""CREATE VIEW TopDevelopers AS
SELECT d.developer, COUNT(a.app_id) AS total_apps
FROM developers d
LEFT JOIN applications a ON d.developer_id = a.developer_id
GROUP BY d.developer_id, d.developer
ORDER BY total_apps DESC;
 """)

In [36]:
# Author Name - Swarn Gaba

# Executing SQL query to select the top 10 developers from the 'TopDevelopers' view
c.execute("""SELECT * 
FROM TopDevelopers
LIMIT 10;
""")

# Fetching and printing the result of the query
c.fetchall()

[('Zinio Pro', 6),
 ('ChowNow', 6),
 ('Magzter Inc.', 5),
 ('Tecniche Nuove spa', 4),
 ('Gray Television Group, Inc.', 4),
 ('LIN Television Corporation', 4),
 ('Jason Stafford', 4),
 ('Sinclair Broadcast Group, Inc', 4),
 ('Kappboom Inc.', 3),
 ('MagazineCloner.com Limited', 3)]

In [37]:
# Author Name - Gandhar Ravindra Pansare

# Free Applications View: Cataloging Free Apps
# Creating a view named 'FreeApplications' to list free applications along with their developers

c.execute("""CREATE VIEW FreeApplications AS
SELECT a.app_name, d.developer
FROM applications a
JOIN developers d ON a.developer_id = d.developer_id
JOIN pricing p ON a.app_id = p.app_id
WHERE p.price = 0;
 """)

In [38]:
# Author Name - Gandhar Ravindra Pansare

# Executing SQL query to select the first 15 records from the 'FreeApplications' view
c.execute("""SELECT * 
FROM FreeApplications
LIMIT 15;
""")

# Fetching and printing the result of the query
c.fetchall()

[('Iglesia Metropolitana', 'Rafael Jimenez'),
 ('Truyện Ma Quỷ', 'Tran Anh'),
 ('Kisah Nabi Ishaq AS', 'EDUCA SISFOMEDIA INDONESIA, CV'),
 ('JKS', 'Jozef Macko'),
 ('LQ-Port Library', '特定非営利活動法人 青少年育成支援フォーラム(JIYD)'),
 ('Goboken', 'Sandviks AS'),
 ('Cuentico Amarillo Tom Sóyer', 'Panter'),
 ('Striding Bird - An inspirational tale for kids', 'Comicorp'),
 ('Liman Kitap Mobil', 'IMST Bilişim'),
 ('How Kiwi Lost His Wings', 'Miha Grcar'),
 ('FC Yearbooks', 'Yearbooker, Inc.'),
 ('Savitri by Sri Aurobindo', 'Revealing Hour Creations'),
 ('LokaNiti', 'Bue Bu'),
 ('Sunshine Bookroom', 'WENDY PYE PUBLISHING LIMITED'),
 ('Literature Audiobooks', 'Rohit Kanade')]

In [39]:
# Author Name - Chaithra Lal Nair

# View of Top-Rated Apps per Genre: Identifying the Highest Rated Applications by Genre
# Creating a view named 'TopRatedAppsByGenre' to showcase applications with the highest user ratings categorized by genre.

c.execute("""CREATE VIEW TopRatedAppsByGenre AS
SELECT a.genre, a.app_name, a.avg_user_rating
FROM applications a
WHERE a.avg_user_rating IS NOT NULL
AND a.avg_user_rating > 3
ORDER BY a.avg_user_rating DESC;
 """)

In [40]:
# Author Name - Chaithra Lal Nair

# Executing SQL query to select the top 10 rated apps in the 'Book' genre from the 'TopRatedAppsByGenre' view
c.execute("""SELECT * 
FROM TopRatedAppsByGenre as t
WHERE t.genre = 'Book'
LIMIT 10;
""")

# Fetching and printing the result of the query
c.fetchall()

[('Book', 'Striding Bird - An inspirational tale for kids', 5.0),
 ('Book', 'Liman Kitap Mobil', 5.0),
 ('Book', 'Savitri by Sri Aurobindo', 5.0),
 ('Book', 'Dorința Mariei', 5.0),
 ('Book', 'Smart Book', 5.0),
 ('Book', 'Kids In A Chip', 5.0),
 ('Book', 'Abdelbaset Abdessamad-Quran mp3-عبدالباسط عبدالصمد', 5.0),
 ('Book', 'Old Mother Hubbard Interactive eBook', 5.0),
 ('Book', 'Al Sudais-السديس', 5.0),
 ('Book', 'Bible+Diary Lite', 5.0)]

In [41]:
# Author Name - Chaithra Lal Nair

# Executing SQL query to select the top 10 rated apps in the 'Games' genre from the 'TopRatedAppsByGenre' view
c.execute("""SELECT * 
FROM TopRatedAppsByGenre as t
WHERE t.genre = 'Games'
LIMIT 10;
""")

# Fetching and printing the result of the query
c.fetchall()

[('Games', 'Crush 64', 5.0),
 ('Games', 'Upstream: Combat Climate Change', 5.0),
 ('Games', 'Circle Crush - Black Edition', 5.0),
 ('Games', 'Super Balloon Shop', 5.0),
 ('Games', 'Drifty Bike', 5.0),
 ('Games', 'Numpops - Brain Games For Kids', 5.0),
 ('Games', 'Hit and Fly', 5.0),
 ('Games', 'Chess Puzz', 4.83333),
 ('Games', 'Bubble Cats- Bubble pop game', 4.82759),
 ('Games', 'Lights: Out', 4.81818)]